import React, { useRef, useMemo, useState } from 'react';
import {
    View, Text, StyleSheet, TouchableOpacity, Image, ScrollView,
    SafeAreaView, Alert, ActivityIndicator, Modal, TextInput, KeyboardAvoidingView, Platform
} from 'react-native';
import { MaterialIcons, Ionicons } from '@expo/vector-icons';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { useTheme } from '@/src/context/ThemeContext';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { transactionService } from '@/src/api/transactionService';
import { Transaction } from '@/src/types/index';
import { captureRef } from 'react-native-view-shot';
import * as Sharing from 'expo-sharing';

export default function TransactionDetailScreen() {
    const router = useRouter();
    const queryClient = useQueryClient();
    const { colors, isDark } = useTheme();
    const { id } = useLocalSearchParams();
    const viewShotRef = useRef<View>(null);

    // --- STATE CHO MODAL CẬP NHẬT ---
    const [isEditModalVisible, setEditModalVisible] = useState(false);
    const [editAmount, setEditAmount] = useState('');
    const [editNote, setEditNote] = useState('');
    const [editType, setEditType] = useState('');

    // 1. LẤY DỮ LIỆU
    const { data: response, isLoading } = useQuery({
        queryKey: ['transactions'],
        queryFn: () => transactionService.getAll(),
    });

    const transaction = useMemo(() => {
        const allTransactions = response?.data?.data || [];
        return allTransactions.find((t: Transaction) => t.id === id);
    }, [response, id]);

    // --- MỞ MODAL VÀ ĐỔ DỮ LIỆU CŨ ---
    const openEditModal = () => {
        if (transaction) {
            setEditAmount(transaction.amount.toLocaleString('vi-VN'));
            setEditNote(transaction.note || '');
            setEditType(transaction.type);
            setEditModalVisible(true);
        }
    };

    // 2. LOGIC CẬP NHẬT (Gửi PUT tới Backend)
    const updateMutation = useMutation({
        mutationFn: (updatedData: any) => transactionService.update(id as string, updatedData),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['transactions'] });
            Alert.alert('Thành công', 'Đã cập nhật giao dịch.');
            setEditModalVisible(false);
        },
        onError: () => {
            Alert.alert('Lỗi', 'Không thể cập nhật giao dịch.');
        }
    });

    const handleSaveUpdate = () => {
        const amountNum = parseFloat(editAmount);

        if (!editAmount || isNaN(amountNum) || amountNum <= 0) {
            Alert.alert('Lỗi', 'Vui lòng nhập số tiền hợp lệ.');
            return;
        }
        if (amountNum > 1000000000) {
            Alert.alert('Giới hạn', 'Số tiền không được vượt quá 1 tỷ VND.');
            return;
        }

        updateMutation.mutate({
            categoryId: transaction?.categoryId,
            amount: amountNum,
            type: transaction?.type,
            note: editNote,
            isAuto: transaction?.isAutoGenerated || false
        });
    };

    // 3. LOGIC XÓA (Gửi DELETE tới Backend)
    const deleteMutation = useMutation({
        mutationFn: () => transactionService.delete(id as string),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['transactions'] });
            Alert.alert('Thành công', 'Đã xóa giao dịch.');
            router.back();
        },
    });

    const handleDelete = () => {
        Alert.alert('Xác nhận xóa', 'Bạn có chắc chắn muốn xóa giao dịch này không?', [
            { text: 'Hủy', style: 'cancel' },
            { text: 'Xóa', style: 'destructive', onPress: () => deleteMutation.mutate() }
        ]);
    };

    const handleShareReceipt = async () => {
        try {
            const uri = await captureRef(viewShotRef, { format: 'png', quality: 1 });
            await Sharing.shareAsync(uri);
        } catch (error) {
            Alert.alert("Lỗi", "Không thể tạo ảnh chia sẻ.");
        }
    };

    if (isLoading) return <View style={styles.centered}><ActivityIndicator size="large" color="#1a237e" /></View>;
    if (!transaction) return <View style={styles.centered}><Text>Không tìm thấy dữ liệu.</Text></View>;

    const isExpense = transaction.type === 'EXPENSE';

    return (
        <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]}>
            {/* Header */}
            <View style={styles.header}>
                <TouchableOpacity onPress={() => router.back()} style={styles.iconBtn}>
                    <MaterialIcons name="arrow-back" size={24} color="#1a237e" />
                </TouchableOpacity>
                <Text style={styles.headerTitle}>Chi tiết giao dịch</Text>
                <TouchableOpacity onPress={handleShareReceipt} style={styles.iconBtn}>
                    <Ionicons name="share-social-outline" size={24} color="#1a237e" />
                </TouchableOpacity>
            </View>

            <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scrollContent}>
                <View style={styles.amountSection}>
                    <Text style={[styles.amountText, { color: isExpense ? '#8B0000' : '#1b6d24' }]}>
                        {isExpense ? '-' : '+'}{transaction.amount.toLocaleString('vi-VN')} VND
                    </Text>
                    <View style={[styles.badge, { backgroundColor: isExpense ? '#FFEBEE' : '#E8F5E9' }]}>
                        <View style={[styles.badgeDot, { backgroundColor: isExpense ? '#D32F2F' : '#2E7D32' }]} />
                        <Text style={[styles.badgeText, { color: isExpense ? '#D32F2F' : '#2E7D32' }]}>
                            {isExpense ? 'KHOẢN CHI TIÊU' : 'KHOẢN THU NHẬP'}
                        </Text>
                    </View>
                </View>

                <View style={[styles.infoCard, { backgroundColor: colors.surface }]}>
                    <View style={styles.cardHeader}>
                        <View style={[styles.categoryIcon, { backgroundColor: (transaction.categoryColor || '#1a237e') + '15' }]}>
                            <MaterialIcons name={(transaction.categoryIcon as any) || 'receipt'} size={28} color={transaction.categoryColor || '#1a237e'} />
                        </View>
                        <View style={styles.categoryInfo}>
                            <Text style={styles.categoryName}>{transaction.categoryName}</Text>
                            <Text style={styles.locationText}>{transaction.isAutoGenerated ? 'Tự động' : 'Thủ công'}</Text>
                        </View>
                    </View>
                    <View style={styles.divider} />
                    <DetailItem icon="calendar-today" label="THỜI GIAN" value={transaction.transactionDate} />
                    <DetailItem icon="description" label="GHI CHÚ" value={transaction.note || 'Không có ghi chú'} />
                    <DetailItem icon="account-balance-wallet" label="TÀI KHOẢN" value="Ví ATPK chính" isLast />
                </View>
            </ScrollView>

            <View style={styles.footer}>
                <TouchableOpacity style={[styles.editBtn, { backgroundColor: isDark ? '#333' : '#F5F5F5' }]} onPress={openEditModal}>
                    <MaterialIcons name="edit" size={20} color={isDark ? '#fff' : '#333'} />
                    <Text style={[styles.editBtnText, { color: isDark ? '#fff' : '#333' }]}>Chỉnh sửa</Text>
                </TouchableOpacity>

                <TouchableOpacity style={styles.deleteBtn} onPress={handleDelete}>
                    <MaterialIcons name="delete-outline" size={20} color="#fff" />
                    <Text style={styles.deleteBtnText}>Xóa</Text>
                </TouchableOpacity>
            </View>

            {/* --- MODAL CHỈNH SỬA --- */}
            <Modal visible={isEditModalVisible} animationType="slide" transparent={true}>
                <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'} style={styles.modalOverlay}>
                    <View style={[styles.modalContent, { backgroundColor: colors.surface }]}>
                        <View style={styles.modalHeader}>
                            <Text style={styles.modalTitle}>Sửa giao dịch</Text>
                            <TouchableOpacity onPress={() => setEditModalVisible(false)}>
                                <MaterialIcons name="close" size={24} color={colors.text} />
                            </TouchableOpacity>
                        </View>

                        <Text style={styles.inputLabel}>Số tiền (Không vượt hơn 1 tỷ)</Text>
                        <TextInput
                            style={[styles.input, { color: colors.text, borderColor: colors.divider }]}
                            keyboardType="numeric"
                            value={editAmount.replace(/\B(?=(\d{3})+(?!\d))/g, ".")}
                            onChangeText={(text) => {
                                // Loại bỏ tất cả ký tự không phải số trước khi lưu vào state
                                const cleanNumber = text.replace(/[^0-9]/g, "");
                                if (Number(cleanNumber) <= 1000000000) {
                                    setEditAmount(cleanNumber);
                                }
                            }}
                            placeholder="Nhập số tiền..."
                        />

                        <Text style={styles.inputLabel}>Ghi chú</Text>
                        <TextInput
                            style={[styles.input, { color: colors.text, borderColor: colors.divider, height: 80 }]}
                            multiline
                            value={editNote}
                            onChangeText={setEditNote}
                            placeholder="Thêm ghi chú..."
                        />
                        <Text style={styles.inputLabel}>Loại giao dịch</Text>
                        <View style={styles.segmentedControl}>
                            {/* Nút Thu Nhập */}
                            <TouchableOpacity
                                style={[
                                    styles.segmentBtn,
                                    editType === 'INCOME' && { backgroundColor: '#4CAF50', borderColor: '#4CAF50' }
                                ]}
                                onPress={() => setEditType('INCOME')} // Nhấn vào là chuyển hẳn sang INCOME
                                activeOpacity={0.8}
                            >
                                <MaterialIcons
                                    name="add-circle-outline"
                                    size={20}
                                    color={editType === 'INCOME' ? '#fff' : '#4CAF50'}
                                />
                                <Text style={[
                                    styles.segmentText,
                                    { color: editType === 'INCOME' ? '#fff' : '#4CAF50' }
                                ]}> Thu nhập</Text>
                            </TouchableOpacity>

                            {/* Nút Chi Tiêu */}
                            <TouchableOpacity
                                style={[
                                    styles.segmentBtn,
                                    editType === 'EXPENSE' && { backgroundColor: '#F44336', borderColor: '#F44336' }
                                ]}
                                onPress={() => setEditType('EXPENSE')} // Nhấn vào là chuyển hẳn sang EXPENSE
                                activeOpacity={0.8}
                            >
                                <MaterialIcons
                                    name="remove-circle-outline"
                                    size={20}
                                    color={editType === 'EXPENSE' ? '#fff' : '#F44336'}
                                />
                                <Text style={[
                                    styles.segmentText,
                                    { color: editType === 'EXPENSE' ? '#fff' : '#F44336' }
                                ]}> Chi tiêu</Text>
                            </TouchableOpacity>
                        </View>

                        <TouchableOpacity
                            style={[styles.saveBtn, { opacity: updateMutation.isPending ? 0.7 : 1 }]}
                            onPress={handleSaveUpdate}
                            disabled={updateMutation.isPending}
                        >
                            {updateMutation.isPending ? <ActivityIndicator color="#fff" /> : <Text style={styles.saveBtnText}>Lưu thay đổi</Text>}
                        </TouchableOpacity>
                    </View>
                </KeyboardAvoidingView>
            </Modal>

            {/* --- BIÊN LAI ẨN --- */}
            <View ref={viewShotRef} collapsable={false} style={styles.hiddenShotContainer}>
                <Text style={styles.shotBrand}>APTK </Text>
                <View style={styles.shotDivider} />
                <Text style={styles.shotLabel}>SỐ TIỀN GIAO DỊCH</Text>
                <Text style={[styles.shotAmountValue, { color: isExpense ? '#8B0000' : '#1b6d24' }]}>
                    {isExpense ? '-' : '+'}{transaction.amount.toLocaleString('vi-VN')} VND
                </Text>
                <View style={styles.shotRow}><Text style={styles.shotRowLabel}>Hạng mục:</Text><Text style={styles.shotRowValue}>{transaction.categoryName}</Text></View>
                <View style={styles.shotRow}><Text style={styles.shotRowLabel}>Ngày:</Text><Text style={styles.shotRowValue}>{transaction.transactionDate}</Text></View>
                <View style={styles.shotRow}><Text style={styles.shotRowLabel}>Ghi chú:</Text><Text style={styles.shotRowValue}>{transaction.note || '---'}</Text></View>
                <Text style={styles.shotFooter}>Giao dịch được quản lý bởi Aeon Ledger</Text>
            </View>
        </SafeAreaView>
    );
}

const DetailItem = ({ icon, label, value, isLast = false }: any) => (
    <View style={[styles.detailItem, isLast && { marginBottom: 0 }]}>
        <MaterialIcons name={icon} size={20} color="#9E9E9E" style={styles.detailIcon} />
        <View style={styles.detailContent}>
            <Text style={styles.detailLabel}>{label}</Text>
            <Text style={styles.detailValue}>{value}</Text>
        </View>
    </View>
);

const styles = StyleSheet.create({
    container: { flex: 1 },
    centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, height: 56 },
    headerTitle: { fontSize: 17, fontWeight: '700', color: '#1a237e' },
    iconBtn: { padding: 8 },
    scrollContent: { paddingHorizontal: 20, paddingBottom: 120 },
    amountSection: { alignItems: 'center', marginVertical: 32 },
    amountText: { fontSize: 32, fontWeight: '900', marginBottom: 12 },
    badge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, gap: 6 },
    badgeDot: { width: 6, height: 6, borderRadius: 3 },
    badgeText: { fontSize: 11, fontWeight: '800', letterSpacing: 0.5 },
    infoCard: { borderRadius: 32, padding: 24, elevation: 4, shadowColor: '#000', shadowOpacity: 0.05 },
    cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
    categoryIcon: { width: 52, height: 52, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
    categoryInfo: { flex: 1, marginLeft: 16 },
    categoryName: { fontSize: 18, fontWeight: 'bold', color: '#1a237e' },
    locationText: { fontSize: 13, color: '#757575' },
    divider: { height: 1, backgroundColor: '#F5F5F5', marginBottom: 20 },
    detailItem: { flexDirection: 'row', marginBottom: 20 },
    detailIcon: { marginTop: 2 },
    detailContent: { marginLeft: 16, flex: 1 },
    detailLabel: { fontSize: 10, fontWeight: '700', color: '#BDBDBD', marginBottom: 4 },
    detailValue: { fontSize: 15, fontWeight: '600', color: '#424242' },
    footer: { position: 'absolute', bottom: 24, left: 20, right: 20, flexDirection: 'row', gap: 12 },
    editBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderRadius: 24, height: 56, gap: 8 },
    editBtnText: { fontSize: 16, fontWeight: '700' },
    deleteBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#4A0404', borderRadius: 24, height: 56, gap: 8 },
    deleteBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },

    // --- STYLE MODAL ---
    modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.5)' },
    modalContent: { borderTopLeftRadius: 32, borderTopRightRadius: 32, padding: 24, paddingBottom: 40 },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
    modalTitle: { fontSize: 20, fontWeight: 'bold', color: '#1a237e' },
    inputLabel: { fontSize: 14, fontWeight: '700', color: '#9E9E9E', marginBottom: 8, marginTop: 12 },
    input: { borderWidth: 1, borderRadius: 12, padding: 12, fontSize: 16 },
    saveBtn: { backgroundColor: '#1a237e', height: 56, borderRadius: 24, justifyContent: 'center', alignItems: 'center', marginTop: 24 },
    saveBtnText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },

    hiddenShotContainer: { position: 'absolute', left: -1000, width: 400, backgroundColor: '#FFF', padding: 40, alignItems: 'center' },
    shotBrand: { fontSize: 32, fontWeight: 'bold', color: '#1a237e', letterSpacing: 3, marginBottom: 20 },
    shotDivider: { width: '100%', height: 1, backgroundColor: '#E0E0E0', marginBottom: 30 },
    shotLabel: { fontSize: 14, color: '#9E9E9E', marginBottom: 10 },
    shotAmountValue: { fontSize: 35, fontWeight: 'bold', marginBottom: 40 },
    shotRow: { flexDirection: 'row', justifyContent: 'space-between', width: '100%', marginBottom: 25 },
    shotRowLabel: { fontSize: 18, color: '#000' },
    shotRowValue: { fontSize: 18, fontWeight: 'bold', color: '#000' },
    shotFooter: { marginTop: 60, fontSize: 14, color: '#BDBDBD' },
    currencyInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderRadius: 12,
        paddingHorizontal: 12,
        height: 56,
        backgroundColor: 'transparent',
    },
    inputRaw: {
        flex: 1,
        fontSize: 18,
        fontWeight: 'bold',
    },
    currencyText: {
        fontSize: 16,
        fontWeight: '700',
        marginLeft: 8,
    },
    segmentedControl: {
        flexDirection: 'row',
        gap: 12, // Khoảng cách giữa 2 nút
        marginTop: 8,
        marginBottom: 16,
    },
    segmentBtn: {
        flex: 1, // Để 2 nút dài bằng nhau
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: 48,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: '#E0E0E0', // Màu viền khi chưa chọn
        backgroundColor: 'transparent',
    },
    segmentText: {
        fontSize: 15,
        fontWeight: 'bold',
        marginLeft: 4,
    },
});