import React, { useRef, useMemo, useState } from 'react';
import {
    View, Text, StyleSheet, TouchableOpacity, ScrollView,
    SafeAreaView, Alert, ActivityIndicator, Modal, TextInput, KeyboardAvoidingView, Platform
} from 'react-native';
import { MaterialIcons, Ionicons } from '@expo/vector-icons';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { useTheme } from '@/src/context/ThemeContext';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { transactionService } from '@/src/api/transactionService';
import { categoryService } from '@/src/api/categoryService'; // Import categoryService
import { Transaction, Category } from '@/src/types/index'; // Import Category
import { captureRef } from 'react-native-view-shot';
import * as Sharing from 'expo-sharing';

export default function TransactionDetailScreen() {
    const router = useRouter();
    const queryClient = useQueryClient();
    const { colors, isDark } = useTheme();
    const { id } = useLocalSearchParams();
    const viewShotRef = useRef<View>(null);

    // --- STATE CHO MODAL CẬP NHẬT ---
    const [isEditModalVisible, setEditModalVisible] = useState(false);
    const [editAmount, setEditAmount] = useState('');
    const [editNote, setEditNote] = useState('');
    const [editType, setEditType] = useState<'EXPENSE' | 'INCOME'>('EXPENSE');
    const [selectedCategoryId, setSelectedCategoryId] = useState<string | null>(null);

    // 1. LẤY DỮ LIỆU GIAO DỊCH HIỆN TẠI
    const { data: response, isLoading } = useQuery({
        queryKey: ['transactions'],
        queryFn: () => transactionService.getAll(),
    });

    const transaction = useMemo(() => {
        if (!response) return undefined;
        const payload = response?.data?.data || response?.data || response;
        const allTransactions = Array.isArray(payload) ? payload : (payload?.data || []);
        return allTransactions.find((t: Transaction) => t.id === id);
    }, [response, id]);

    // 2. LẤY DANH SÁCH DANH MỤC (Dựa theo loại editType đang chọn)
    const {
        data: categoriesData,
        isLoading: isCategoriesLoading
    } = useQuery({
        queryKey: ['categories', editType],
        queryFn: () => categoryService.getAll({ type: editType }),
        enabled: isEditModalVisible, // Chỉ gọi API khi Modal đang mở
    });

    const categories: Category[] = (categoriesData as any)?.data?.data || [];

    // --- MỞ MODAL VÀ ĐỔ DỮ LIỆU CŨ ---
    const openEditModal = () => {
        if (transaction) {
            setEditAmount(transaction.amount.toString()); // Lưu số thuần, không format
            setEditNote(transaction.note || '');
            setEditType(transaction.type as 'EXPENSE' | 'INCOME');
            setSelectedCategoryId(transaction.categoryId || null); // Load danh mục cũ
            setEditModalVisible(true);
        }
    };

    // 3. LOGIC CẬP NHẬT (Gửi PUT tới Backend)
    const updateMutation = useMutation({
        mutationFn: (updatedData: any) => transactionService.update(id as string, updatedData),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['transactions'] });
            queryClient.invalidateQueries({ queryKey: ['userProfile'] }); // Cập nhật số dư ở Dashboard
            queryClient.invalidateQueries({ queryKey: ['budgets'] }); // Cập nhật ngân sách nếu có
            Alert.alert('Thành công', 'Đã cập nhật giao dịch.');
            setEditModalVisible(false);
        },
        onError: () => {
            Alert.alert('Lỗi', 'Không thể cập nhật giao dịch.');
        }
    });

    const handleSaveUpdate = () => {
        const cleanAmountStr = editAmount.replace(/[^0-9]/g, '');
        const amountNum = Number(cleanAmountStr);

        if (!cleanAmountStr || isNaN(amountNum) || amountNum <= 0) {
            Alert.alert('Lỗi', 'Vui lòng nhập số tiền hợp lệ.');
            return;
        }
        if (amountNum > 1000000000) {
            Alert.alert('Giới hạn', 'Số tiền không được vượt quá 1 tỷ VND.');
            return;
        }
        if (!selectedCategoryId) {
            Alert.alert('Thông báo', 'Vui lòng chọn một danh mục.');
            return;
        }

        updateMutation.mutate({
            categoryId: selectedCategoryId, // Gửi danh mục mới
            amount: amountNum,
            type: editType, // Gửi loại mới
            note: editNote.trim(),
            isAuto: transaction?.isAutoGenerated || false
        });
    };

    // 4. LOGIC XÓA (Gửi DELETE tới Backend)
    const deleteMutation = useMutation({
        mutationFn: () => transactionService.delete(id as string),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['transactions'] });
            queryClient.invalidateQueries({ queryKey: ['userProfile'] });
            queryClient.invalidateQueries({ queryKey: ['budgets'] });
            Alert.alert('Thành công', 'Đã xóa giao dịch.');
            router.back();
        },
    });

    const handleDelete = () => {
        Alert.alert('Xác nhận xóa', 'Bạn có chắc chắn muốn xóa giao dịch này không?', [
            { text: 'Hủy', style: 'cancel' },
            { text: 'Xóa', style: 'destructive', onPress: () => deleteMutation.mutate() }
        ]);
    };

    const handleShareReceipt = async () => {
        try {
            const uri = await captureRef(viewShotRef, { format: 'png', quality: 1 });
            await Sharing.shareAsync(uri);
        } catch (error) {
            Alert.alert("Lỗi", "Không thể tạo ảnh chia sẻ.");
        }
    };

    if (isLoading) return <View style={styles.centered}><ActivityIndicator size="large" color="#1a237e" /></View>;
    if (!transaction) return <View style={styles.centered}><Text>Không tìm thấy dữ liệu.</Text></View>;

    const isExpense = transaction.type === 'EXPENSE';

    return (
        <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]}>
            {/* Header */}
            <View style={styles.header}>
                <TouchableOpacity onPress={() => router.back()} style={styles.iconBtn}>
                    <MaterialIcons name="arrow-back" size={24} color="#1a237e" />
                </TouchableOpacity>
                <Text style={styles.headerTitle}>Chi tiết giao dịch</Text>
                <TouchableOpacity onPress={handleShareReceipt} style={styles.iconBtn}>
                    <Ionicons name="share-social-outline" size={24} color="#1a237e" />
                </TouchableOpacity>
            </View>

            <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scrollContent}>
                <View style={styles.amountSection}>
                    <Text style={[styles.amountText, { color: isExpense ? '#8B0000' : '#1b6d24' }]}>
                        {isExpense ? '-' : '+'}{transaction.amount.toLocaleString('vi-VN')} VND
                    </Text>
                    <View style={[styles.badge, { backgroundColor: isExpense ? '#FFEBEE' : '#E8F5E9' }]}>
                        <View style={[styles.badgeDot, { backgroundColor: isExpense ? '#D32F2F' : '#2E7D32' }]} />
                        <Text style={[styles.badgeText, { color: isExpense ? '#D32F2F' : '#2E7D32' }]}>
                            {isExpense ? 'KHOẢN CHI TIÊU' : 'KHOẢN THU NHẬP'}
                        </Text>
                    </View>
                </View>

                <View style={[styles.infoCard, { backgroundColor: colors.surface }]}>
                    <View style={styles.cardHeader}>
                        <View style={[styles.categoryIcon, { backgroundColor: (transaction.categoryColor || '#1a237e') + '15' }]}>
                            <MaterialIcons name={(transaction.categoryIcon as any) || 'receipt'} size={28} color={transaction.categoryColor || '#1a237e'} />
                        </View>
                        <View style={styles.categoryInfo}>
                            <Text style={styles.categoryName}>{transaction.categoryName}</Text>
                            <Text style={styles.locationText}>{transaction.isAutoGenerated ? 'Tự động' : 'Thủ công'}</Text>
                        </View>
                    </View>
                    <View style={styles.divider} />
                    <DetailItem icon="calendar-today" label="THỜI GIAN" value={transaction.transactionDate} />
                    <DetailItem icon="description" label="GHI CHÚ" value={transaction.note || 'Không có ghi chú'} />
                    <DetailItem icon="account-balance-wallet" label="TÀI KHOẢN" value="Ví ATPK chính" isLast />
                </View>
            </ScrollView>

            <View style={styles.footer}>
                <TouchableOpacity style={[styles.editBtn, { backgroundColor: isDark ? '#333' : '#F5F5F5' }]} onPress={openEditModal}>
                    <MaterialIcons name="edit" size={20} color={isDark ? '#fff' : '#333'} />
                    <Text style={[styles.editBtnText, { color: isDark ? '#fff' : '#333' }]}>Chỉnh sửa</Text>
                </TouchableOpacity>

                <TouchableOpacity style={styles.deleteBtn} onPress={handleDelete}>
                    <MaterialIcons name="delete-outline" size={20} color="#fff" />
                    <Text style={styles.deleteBtnText}>Xóa</Text>
                </TouchableOpacity>
            </View>

            {/* --- MODAL CHỈNH SỬA (CẬP NHẬT CÓ PHẦN CHỌN DANH MỤC) --- */}
            <Modal visible={isEditModalVisible} animationType="slide" transparent={true}>
                <View style={styles.modalOverlay}>
                    <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'} style={styles.modalContent}>
                        <View style={styles.modalHeader}>
                            <Text style={styles.modalTitle}>Sửa giao dịch</Text>
                            <TouchableOpacity onPress={() => setEditModalVisible(false)}>
                                <MaterialIcons name="close" size={28} color="#1a237e" />
                            </TouchableOpacity>
                        </View>

                        <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 40 }}>
                            
                            {/* 1. NÚT CHỌN LOẠI */}
                            <View style={styles.typeSelector}>
                                <TouchableOpacity
                                    style={[styles.typeBtn, editType === 'EXPENSE' && styles.typeBtnActiveExpense]}
                                    onPress={() => {
                                        if (editType !== 'EXPENSE') {
                                            setEditType('EXPENSE');
                                            setSelectedCategoryId(null); // Reset danh mục khi đổi loại
                                        }
                                    }}
                                >
                                    <Text style={[styles.typeText, editType === 'EXPENSE' && styles.typeTextActive]}>Chi tiêu</Text>
                                </TouchableOpacity>
                                <TouchableOpacity
                                    style={[styles.typeBtn, editType === 'INCOME' && styles.typeBtnActiveIncome]}
                                    onPress={() => {
                                        if (editType !== 'INCOME') {
                                            setEditType('INCOME');
                                            setSelectedCategoryId(null); // Reset danh mục khi đổi loại
                                        }
                                    }}
                                >
                                    <Text style={[styles.typeText, editType === 'INCOME' && styles.typeTextActive]}>Thu nhập</Text>
                                </TouchableOpacity>
                            </View>

                            {/* 2. NHẬP SỐ TIỀN */}
                            <Text style={styles.inputLabel}>Số tiền (Không vượt hơn 1 tỷ)</Text>
                            <TextInput
                                style={[styles.input, { color: colors.text, borderColor: colors.divider }]}
                                keyboardType="numeric"
                                value={editAmount ? Number(editAmount).toLocaleString('vi-VN') : ''}
                                onChangeText={(text) => {
                                    const cleanNumber = text.replace(/[^0-9]/g, "");
                                    if (Number(cleanNumber) <= 1000000000) {
                                        setEditAmount(cleanNumber);
                                    }
                                }}
                                placeholder="Nhập số tiền..."
                            />

                            {/* 3. CHỌN DANH MỤC */}
                            <Text style={styles.inputLabel}>Danh mục</Text>
                            {isCategoriesLoading ? (
                                <ActivityIndicator size="small" color="#1a237e" style={{ marginVertical: 10 }} />
                            ) : categories.length === 0 ? (
                                <Text style={{ color: '#767683', fontStyle: 'italic', marginBottom: 16 }}>Chưa có danh mục nào cho loại này.</Text>
                            ) : (
                                <View style={styles.categoryGrid}>
                                    {categories.map((cat) => (
                                        <TouchableOpacity
                                            key={cat.id}
                                            style={[
                                                styles.categoryItem,
                                                selectedCategoryId === cat.id && { borderColor: cat.color, backgroundColor: cat.color + '10' }
                                            ]}
                                            onPress={() => setSelectedCategoryId(cat.id)}
                                        >
                                            <View style={[styles.iconCircle, { backgroundColor: cat.color + '40' }]}>
                                                <MaterialIcons name={cat.icon as any} size={24} color={cat.color} />
                                            </View>
                                            <Text style={styles.categoryText} numberOfLines={1}>{cat.name}</Text>
                                        </TouchableOpacity>
                                    ))}
                                </View>
                            )}

                            {/* 4. GHI CHÚ */}
                            <Text style={styles.inputLabel}>Ghi chú</Text>
                            <TextInput
                                style={[styles.input, { color: colors.text, borderColor: colors.divider, height: 80 }]}
                                multiline
                                value={editNote}
                                onChangeText={setEditNote}
                                placeholder="Thêm ghi chú..."
                            />

                            {/* 5. NÚT LƯU */}
                            <TouchableOpacity
                                style={[styles.saveBtn, { opacity: updateMutation.isPending ? 0.7 : 1 }]}
                                onPress={handleSaveUpdate}
                                disabled={updateMutation.isPending}
                            >
                                {updateMutation.isPending ? <ActivityIndicator color="#fff" /> : <Text style={styles.saveBtnText}>Lưu thay đổi</Text>}
                            </TouchableOpacity>
                        </ScrollView>
                    </KeyboardAvoidingView>
                </View>
            </Modal>

            {/* --- BIÊN LAI ẨN --- */}
            <View ref={viewShotRef} collapsable={false} style={styles.hiddenShotContainer}>
                <Text style={styles.shotBrand}>APTK </Text>
                <View style={styles.shotDivider} />
                <Text style={styles.shotLabel}>SỐ TIỀN GIAO DỊCH</Text>
                <Text style={[styles.shotAmountValue, { color: isExpense ? '#8B0000' : '#1b6d24' }]}>
                    {isExpense ? '-' : '+'}{transaction.amount.toLocaleString('vi-VN')} VND
                </Text>
                <View style={styles.shotRow}><Text style={styles.shotRowLabel}>Hạng mục:</Text><Text style={styles.shotRowValue}>{transaction.categoryName}</Text></View>
                <View style={styles.shotRow}><Text style={styles.shotRowLabel}>Ngày:</Text><Text style={styles.shotRowValue}>{transaction.transactionDate}</Text></View>
                <View style={styles.shotRow}><Text style={styles.shotRowLabel}>Ghi chú:</Text><Text style={styles.shotRowValue}>{transaction.note || '---'}</Text></View>
                <Text style={styles.shotFooter}>Giao dịch được quản lý bởi Aeon Ledger</Text>
            </View>
        </SafeAreaView>
    );
}

const DetailItem = ({ icon, label, value, isLast = false }: any) => (
    <View style={[styles.detailItem, isLast && { marginBottom: 0 }]}>
        <MaterialIcons name={icon} size={20} color="#9E9E9E" style={styles.detailIcon} />
        <View style={styles.detailContent}>
            <Text style={styles.detailLabel}>{label}</Text>
            <Text style={styles.detailValue}>{value}</Text>
        </View>
    </View>
);

const styles = StyleSheet.create({
    container: { flex: 1 },
    centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, height: 56 },
    headerTitle: { fontSize: 17, fontWeight: '700', color: '#1a237e' },
    iconBtn: { padding: 8 },
    scrollContent: { paddingHorizontal: 20, paddingBottom: 120 },
    amountSection: { alignItems: 'center', marginVertical: 32 },
    amountText: { fontSize: 32, fontWeight: '900', marginBottom: 12 },
    badge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, gap: 6 },
    badgeDot: { width: 6, height: 6, borderRadius: 3 },
    badgeText: { fontSize: 11, fontWeight: '800', letterSpacing: 0.5 },
    infoCard: { borderRadius: 32, padding: 24, elevation: 4, shadowColor: '#000', shadowOpacity: 0.05 },
    cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
    categoryIcon: { width: 52, height: 52, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
    categoryInfo: { flex: 1, marginLeft: 16 },
    categoryName: { fontSize: 18, fontWeight: 'bold', color: '#1a237e' },
    locationText: { fontSize: 13, color: '#757575' },
    divider: { height: 1, backgroundColor: '#F5F5F5', marginBottom: 20 },
    detailItem: { flexDirection: 'row', marginBottom: 20 },
    detailIcon: { marginTop: 2 },
    detailContent: { marginLeft: 16, flex: 1 },
    detailLabel: { fontSize: 10, fontWeight: '700', color: '#BDBDBD', marginBottom: 4 },
    detailValue: { fontSize: 15, fontWeight: '600', color: '#424242' },
    footer: { position: 'absolute', bottom: 24, left: 20, right: 20, flexDirection: 'row', gap: 12 },
    editBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderRadius: 24, height: 56, gap: 8 },
    editBtnText: { fontSize: 16, fontWeight: '700' },
    deleteBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#4A0404', borderRadius: 24, height: 56, gap: 8 },
    deleteBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },

    // --- STYLE MODAL ---
    modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.5)' },
    modalContent: { backgroundColor: '#fff', borderTopLeftRadius: 32, borderTopRightRadius: 32, padding: 24, paddingTop: 32, maxHeight: '85%' },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    modalTitle: { fontSize: 22, fontWeight: 'bold', color: '#1a237e' },
    inputLabel: { fontSize: 14, fontWeight: '700', color: '#9E9E9E', marginBottom: 12, marginTop: 20 },
    input: { borderWidth: 1, borderRadius: 16, padding: 16, fontSize: 16 },
    saveBtn: { backgroundColor: '#1a237e', height: 56, borderRadius: 24, justifyContent: 'center', alignItems: 'center', marginTop: 32 },
    saveBtnText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },

    // --- STYLES MỚI CHO PHẦN CHỌN LOẠI & DANH MỤC TRONG MODAL ---
    typeSelector: { flexDirection: 'row', backgroundColor: '#f5f2fb', borderRadius: 16, padding: 4, marginTop: 10 },
    typeBtn: { flex: 1, paddingVertical: 12, alignItems: 'center', borderRadius: 12 },
    typeBtnActiveExpense: { backgroundColor: '#ff635f' },
    typeBtnActiveIncome: { backgroundColor: '#1b6d24' },
    typeText: { fontSize: 15, fontWeight: 'bold', color: '#767683' },
    typeTextActive: { color: '#ffffff' },
    categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, width: '100%' },
    categoryItem: { width: '30%', aspectRatio: 1, borderRadius: 20, borderWidth: 1, borderColor: '#f5f2fb', backgroundColor: '#f5f2fb', alignItems: 'center', justifyContent: 'center', gap: 8 },
    iconCircle: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
    categoryText: { fontSize: 12, fontWeight: '600', color: '#454652', textAlign: 'center' },

    // --- STYLES CHO BIÊN LAI ---
    hiddenShotContainer: { position: 'absolute', left: -1000, width: 400, backgroundColor: '#FFF', padding: 40, alignItems: 'center' },
    shotBrand: { fontSize: 32, fontWeight: 'bold', color: '#1a237e', letterSpacing: 3, marginBottom: 20 },
    shotDivider: { width: '100%', height: 1, backgroundColor: '#E0E0E0', marginBottom: 30 },
    shotLabel: { fontSize: 14, color: '#9E9E9E', marginBottom: 10 },
    shotAmountValue: { fontSize: 35, fontWeight: 'bold', marginBottom: 40 },
    shotRow: { flexDirection: 'row', justifyContent: 'space-between', width: '100%', marginBottom: 25 },
    shotRowLabel: { fontSize: 18, color: '#000' },
    shotRowValue: { fontSize: 18, fontWeight: 'bold', color: '#000' },
    shotFooter: { marginTop: 60, fontSize: 14, color: '#BDBDBD' },
});