export type TransactionType = "INCOME" | "EXPENSE";
export type BudgetType = "SAVING" | "LIMIT";
export type FrequencyType = "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY";
export type DebtLoanType = "DEBT" | "LOAN";
export type DebtLoanStatus = "ONGOING" | "COMPLETED" | "OVERDUE";


export interface User {
    id: string;
    userId: string;
    fullName: string;
    phone: string;
    displayName: string;
    photoUrl: string;
    username: string;
    categoryId: string;
    email: string;
    currentBalance: number;
    createdAt: number | string;
    updatedAt: number | string;
}

export interface SalaryConfig {
    id: string;
    userId: string;
    amount: number;
    payday: number; // Ngày trong tháng
    isActive: boolean;
    lastTriggered: number | string | null;
    createdAt: number | string;
    updatedAt: number | string;
}

export interface Category {
    id: string;
    userId: string;
    name: string;
    type: TransactionType;
    color: string;
    icon: string;
    is_archived: boolean;
    createdAt: number | string;
    updatedAt: number | string;
}

export interface Transaction {
    id: string;
    userId: string;
    amount: number;
    categoryName: string;
    categoryId: string;
    type: TransactionType;
    categoryIcon: string;
    categoryColor: string;
    isAutoGenerated: boolean;
    note?: string;
    transactionDate: number | string;
    createdAt: number | string;
    updatedAt: number | string;
}

export interface Budget {
    id: string;
    userId: string;
    name: string;
    targetAmount: number;
    currentAmount: number;
    type: BudgetType;
    categoryId?: string;
    categoryIcon: string;
    categoryColor: string;
    monthYear: string;
    createdAt: number | string;
    updatedAt: number | string;
}

export interface RecurringTransaction {
    id: string;
    userId: string;
    categoryId: string;
    name: string;
    amount: number;
    type: TransactionType;
    frequency: FrequencyType;
    every: number;
    nextTriggerDate: number;
    lastTriggerDate?: number;
    endDate?: number;
    autoApply: boolean;
    isActive: boolean;
}

export interface DebtLoan {
    id: string;
    userId: string;
    contactName: string;
    phoneNumber?: string;
    type: DebtLoanType;
    totalAmount: number;
    paidAmount: number;
    remainingAmount: number;
    status: DebtLoanStatus;
    startDate?: number;
    dueDate?: number;
    interestRate?: number;
    note?: string;
    isActive: boolean;
}