spring.application.name=finance-management
server.port=8082

# 1. K\u1EBFt n\u1ED1i MySQL (\u0110\u00E3 ch\u1EA1y ngon)
spring.datasource.url=jdbc:mysql://localhost:3306/finance_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=vantuan
spring.datasource.password=2907
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. C\u1EA5u h\u00ECnh JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# T\u1EAFt c\u00E1i c\u1EA3nh b\u00E1o Open-In-View trong log c\u1EE7a b\u1EA1n
spring.jpa.open-in-view=false

# 3. \u00C9p Spring Security kh\u00F4ng t\u1EF1 t\u1EA1o Password ng\u1EABu nhi\u00EAn
spring.security.user.name=user
spring.security.user.password=123
spring.main.allow-bean-definition-overriding=true